### ISSUE TITLE
ansible 

### ISSUE THREAD

**Issue by fuhaha** [openstack-kr/openstack-study#11]
[rst1_file.txt](https://github.com/openstack-kr/openstack-study/files/408885/rst1_file.txt)
[rst2_setup.txt](https://github.com/openstack-kr/openstack-study/files/408892/rst2_setup.txt)
[rst3_file.txt](https://github.com/openstack-kr/openstack-study/files/408883/rst3_file.txt)
[rst4_copy.txt](https://github.com/openstack-kr/openstack-study/files/408884/rst4_copy.txt)
[rst5_command.txt](https://github.com/openstack-kr/openstack-study/files/408882/rst5_command.txt)
[rst6_file.txt](https://github.com/openstack-kr/openstack-study/files/408886/rst6_file.txt)
[rst7_shell.txt](https://github.com/openstack-kr/openstack-study/files/408887/rst7_shell.txt)

**Comment by ianychoi** [comment]
https://github.com/fuhaha/ansible_study/ 에 최종 업데이트되었기에 close 합니다 :)
